### PR TITLE
fix: added rose pattern animation (#71)

### LINKED ISSUE #71: simulations: rose pattern: Add rose pattern Animation
Animate Rose Pattern like Lissajous Curve simulation, see #70

### PR DESCRIPTION
**Pull request by 991rajat**
Fixed #71

### CODE REVIEW

**Review by sakshamarora1 — CHANGES_REQUESTED** [review]
Nice work!
Just a few things - 
- When both the numerator and denominator are 0, an error is thrown & both `k ~` and `animate` checkbox get dislocated. Can you take a look at that? and let me know if there are any doubts.
- I think we need to refactor the code a bit so that the pattern doesn't go out of screen when `Offset` value is increased.
- Also, we can make the animation a bit faster. :)

**Comment by 991rajat** [comment]
@sakshamarora1 
I need help with the second point.

> (I think we need to refactor the code a bit so that the pattern doesn't go out of screen when Offset value is increased.)

File: lib/src/simulations/rose_pattern.dart [hunk 1]
```diff
@@ -58,6 +62,49 @@ class _RosePatternState extends State<RosePattern> {
...
+                  setState(() {
+                    globalKey.currentState.clearScreen();
+                  });
+                },
+              ),
+            ],
+          ),
+        ),
+      ),
       bottomNavigationBar: Container(
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart:109]: This is an older simulation so we haven't implemented a `ListView` widget like in Lissajous Curve. Just change the Column child to ListView similarly to how it's been done in [Lissajous Curve](https://github.com/cod-ed/simulate/blob/master/lib/src/simulations/lissajous_curve.dart).

File: lib/src/simulations/rose_pattern.dart [hunk 2]
```diff
@@ -154,32 +198,139 @@ class _RosePatternState extends State<RosePattern> {
...
+  double loopi = 0;
+  double r, k;
+  double looplength = 2 * pi;
+
+
+  void dispose() {
+    super.dispose();
+  }
+
+  void clearScreen() {
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart:257]: When the screen is cleared,the simulation starts from the beginning. Instead we can have it start right where it left off. That would become the starting point for the animation!
For reference you can check out [Lissajous Curve](https://github.com/cod-ed/simulate/blob/master/lib/src/simulations/lissajous_curve.dart).

File: lib/src/simulations/rose_pattern.dart [hunk 3]
```diff
@@ -154,32 +198,139 @@ class _RosePatternState extends State<RosePattern> {
...
+    if(loopi>=looplength)
+    {
+      clearScreen();
+      looplength = 2 * pi * widget.d;
+      loopi = 0;
+    }
+
+    setState(() {
+      if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
+        sleep(Duration(milliseconds: 1));
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart]: Can you make the animation a bit faster while keeping it smooth? I tried changing these values but couldn't find a good match.

**Review by sakshamarora1 — COMMENTED** [review]
Don't worry about the offset issue as it looks fine as it is for now. We can take care of that later if need be.
Just a few minor changes left.

File: lib/src/simulations/rose_pattern.dart [hunk 4]
```diff
@@ -260,7 +255,7 @@ class _RoseState extends State<Rose> {
   void clearScreen() {
     points.clear();
     looplength = 2 * pi * widget.d;
-    loopi=0;
+    looplength+=loopi;
   }
 
   nextStep()
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart]: `looplength = 2 * pi * widget.d;` in the if statement is not needed as we are updating looplength in `clearScreen()`.

File: lib/src/simulations/rose_pattern.dart [hunk 5]
```diff
@@ -274,8 +269,7 @@ class _RoseState extends State<Rose> {
 
     setState(() {
       if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
-        sleep(Duration(milliseconds: 1));
-        loopi += 0.01;
+        loopi += 0.05;
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart]:
```suggestion
        loopi += 0.04;
```

File: lib/src/simulations/rose_pattern.dart [hunk 6]
```diff
@@ -274,8 +269,7 @@ class _RoseState extends State<Rose> {
 
     setState(() {
       if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
```
Comment (sakshamarora1) [inline lib/src/simulations/rose_pattern.dart]:
```suggestion
      if(loopi == 0) {
        looplength = 2 * pi * widget.d;
      }
      if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
```

`looplength` depends on `widget.d` that's why the first animation is always short, because initially it's value is 2pi and is not multiplied by `widget.d`.

**Review by sakshamarora1 — COMMENTED** [review]
I noticed the first animation was not completing the pattern. Also change the height of bottom navigation bar to be a fifth of the screen instead of fourth of the screen.

Important: As I mentioned before, you haven't considered the case where denominator is equated to 0 while it's animating. Its throwing an exception.

**Comment by 991rajat** [comment]
@sakshamarora1 "As I mentioned before, you haven't considered the case where denominator is equated to 0 while it's animating. Its throwing an exception."
I don't find while running it.

**Comment by sakshamarora1** [comment]
@991rajat That's weird. I was getting that error till yesterday!
